#[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[shell]
program = "/usr/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "F11", mods = "None", action = "ToggleFullscreen" },
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.0
builtin_box_drawing = true

[colors]
draw_bold_text_with_bright_colors = true

[window]
opacity = 1
padding.x = 0
padding.y = 0
decorations = "None" # Full, Buttonless, Transparent, None
